spring:
  application:
    name: lyol
  datasource:
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.name:lyol}?currentSchema=${database.schema:lyol}
    username: ${database.username:postgres}
    password: ${database.password:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximumPoolSize: 50
  jpa:
    generate-ddl: true
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  main:
    web-application-type: none

scheduleFile:
  type: xlsx
  path: src/main/resources/schedule.xlsx

isTestRun: false

#server:
#  port: ${port:1997}
